services:
  database:
    image: postgres:16.6
    command: postgres -c 'max_connections=300'
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=local
    ports:
      - 5434:5432
    shm_size: 1g
    networks:
      - localapp


  emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: 'potatopotato1!'
      ACCEPT_EULA: 'Y'
    depends_on:
      - sqledge
    networks:
      localapp:
        aliases:
          - "sb-emulator"

  sqledge:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      localapp:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'potatopotato1!'  

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/tmp/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/tmp/otel-collector-config.yaml 
    ports:
      - "1888:1888"
      - "8889:8889"
      - "13133:13133"
      - "4381:4318"
      - "55679:55679"
    networks:
      - localapp

  zipkin:
    image: openzipkin/zipkin:latest
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    restart: always
    ports:
      - "9411:9411"
    networks:
      - localapp

networks:
  localapp:
    driver: bridge
    internal: false
